### ISSUE TITLE
no working

### ISSUE THREAD

**Issue by Jackson1603** [br0keh/chknet-capture#5]
Traceback (most recent call last):
File "main.py", line 15, in
bot_name = "%s%i" % (''.join(random.choices(
AttributeError: 'module' object has no attribute 'choices'

**Comment by Jackson1603** [comment]
Traceback (most recent call last):
File "main.py", line 15, in
bot_name = "%s%i" % (''.join(random.choices(
AttributeError: 'module' object has no attribute 'choices'

**Comment by Azeraze123** [comment]
Hi
